### ISSUE TITLE
Question: usage with multiple databases

### ISSUE THREAD

**Issue by validkeys** [romeerez/pg-transactional-tests#1]
Firstly, I love you for this project. It saved me from having to write it and it works great. 

Question for you, my project has multiple databases and therefore multiple connections through PG. My first database connection works flawlessly, however the connection to the second database starts causing errors as the money patched PG is locked into pointing at the first database it connected to. 

Any advice on how to isolate this package on a per database basis?

**Comment by romeerez** [comment]
Thank you for the kind words and for making this world better by writing tests!

> Any advice on how to isolate this package on a per database basis?

Never thought about it so there is no way currently. But the library is small so it shouldn't be too complex to make such a change.

**Comment by romeerez** [comment]
Ready!

v1.1.0 will track different pg clients by their different connection settings (host, port, user, db name) and will run separate transactions per each db.
